### ISSUE TITLE
No EXE found in 3.4 release build!

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/Isra_NPC#7]
Greetings!

I extracted the 3.4 release build on my Windows 10 machine and found no EXE file!

**Comment by GwendolyneFreddy** [comment]
The package contains setup-isra.exe : https://github.com/SpellholdStudios/Isra_NPC/releases/tag/v3.4

**Comment by Endarire** [comment]
Odd.  I seemingly didn't notice it.  Thankee for your help and apologies for the false alert!  Alleluia!
