### ISSUE TITLE
exe file

### ISSUE THREAD

**Issue by ShadowDragun** [SpellholdStudios/Isra_NPC#8]
Hello, I'm new to github and I cannot find the .exe file in 3.4.  I saw the closed issue and clicked on the link but I still cannot find it :(   I'm used to Spellhold studios and am sorry for the inconvenience but I love Isra's mod and am trying to update it.

**Comment by GwendolyneFreddy** [comment]
Can you read files extensions in your game directory? I mean chitin**.key** and so on...

**Comment by GwendolyneFreddy** [comment]
Download the zip file in the [releases tab](https://github.com/SpellholdStudios/Isra_NPC/releases)

**Comment by GwendolyneFreddy** [comment]
Can you read files extensions in your game directory? Such as chitin**.key**, baldur**.exe**...

**Comment by ShadowDragun** [comment]
I tried that as well, and it acted like it unzipped but the files just disappeared like they weren't there. When it was unzipping the chart acted like there were no files.  I'm sorry to be a bother.

**Comment by ShadowDragun** [comment]
Ah I figured it out, my antivirus kept it from working properly.  Sorry to bother you!

**Comment by GwendolyneFreddy** [comment]
My fault.
Should have thought about it as I always write it in the[ readme install section](https://github.com/SpellholdStudios/Isra_NPC#installation)...

**Comment by GwendolyneFreddy** [comment]
closed
